server:
  address: 0.0.0.0
  port: 8085

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
          audiences:
            - 2f01f2a9-d3f9-4275-971d-9581d37c1d9d
            - api://2f01f2a9-d3f9-4275-971d-9581d37c1d9d

springdoc:
  swagger-ui:
    path: /api-groups.html
  api-docs:
    path: /api-groups