server:
  address: 0.0.0.0
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb+srv://WhereWe:fnQ2kZUYqOY2tsK7@wherewe-groups.0liqn.mongodb.net/WhereWe-groups?retryWrites=true&w=majority&appName=WhereWe-groups